apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: springboot-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: springboot-test
    app.kubernetes.io/part-of: my-app
  name: springboot-test
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: springboot-test
status:
  loadBalancer: {}
