apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: upgraded-manner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: upgraded-manner
    app.kubernetes.io/part-of: my-app
  name: upgraded-manner
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: upgraded-manner
status:
  loadBalancer: {}
