apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: upgraded-manner
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/sbudhwar-1-tenant/my-app/upgraded-manner@sha256:8a5c8402b5dfcc9f6d7010d57d00e95e3a556c7114dd1c2b976f51d14ffcdce5
        name: my-java-quarkus
        resources: {}
status: {}
