apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: upgraded-manner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: upgraded-manner
    app.kubernetes.io/part-of: my-app
  name: upgraded-mannergpf1
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: upgraded-manner
    weight: 100
status: {}
